package:
  name: discover
  version: 0.9.4

source:
  path: ..
  patches:
    - arch-core2.patch
    - no-stack-arrays.patch
    - no-lto.patch                  # [osx]
    - restore-old-nan-code.patch    # [osx]

build:
  number: 0
  
  requires_features:
    blas: {{ blas_impl }}
  
  features:
    - nomkl                         # [x86 and blas_impl != 'mkl']

requirements:
  build:
    - {{ compiler('c') }}           # [unix]
    - {{ compiler('fortran') }}     # [unix]
    - m2w64-toolchain               # [win]
    - libpython                     # [win]

  host:
    - python
    - numpy
    - mkl-devel                     # [blas_impl == 'mkl']
    - openblas-devel                # [blas_impl == 'openblas']
    - nomkl                         # [x86 and blas_impl != 'mkl']

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - m2w64-gcc-libs                # [win]
    - m2w64-gcc-libgfortran         # [win]

test:
  requires:
    - nomkl                         # [x86 and blas_impl == 'openblas']
  imports:
    - discover
  commands:
    - conda inspect linkages -p $PREFIX discover      # [not win]
    - conda inspect objects -p $PREFIX discover       # [osx]

about:
  home: http://ccb.nki.nl/software/discover
  license: Apache 2.0
  summary: 'DISCOVER co-occurrence and mutual exclusivity analysis'
